[main]
  extraCommands = ["git push", "git push --tags"]
  serialize = "{version}-{banner}"
  tag = true
  version = "3.0.0"

[[operate]]
  location = "cmd/pocV/pocV.go"
  replace = "__version__ = \"{}\""
  search = "__version__ = \"{}\""